version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/opt"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "/start"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
